# Generated by Django 6.0 on 2025-12-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postagem_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos_analisados', models.IntegerField(default=150, help_text='Número exibido na home', verbose_name='Jogos Analisados')),
                ('videos_por_mes', models.IntegerField(default=15, help_text='Número exibido na home', verbose_name='Vídeos por Mês')),
                ('inscritos_canal', models.IntegerField(default=2000, help_text='Número exibido na home', verbose_name='Inscritos no Canal')),
                ('hero_titulo', models.CharField(default='Bem-vindo à Mesa Secreta', max_length=200, verbose_name='Título Principal')),
                ('hero_descricao', models.TextField(default='Reviews completos, análises profundas e as melhores estratégias para dominar o mundo dos jogos de tabuleiro modernos e RPGs', verbose_name='Descrição Principal')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@mesasecreta', verbose_name='URL do YouTube')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/mesasecreta', verbose_name='URL do Instagram')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com/@mesasecreta', verbose_name='URL do TikTok')),
                ('twitter_url', models.URLField(blank=True, verbose_name='URL do Twitter/X')),
                ('facebook_url', models.URLField(blank=True, verbose_name='URL do Facebook')),
                ('sobre_texto', models.TextField(default='O Quartel General dos jogos de tabuleiro e RPG! Conteúdo de qualidade sobre reviews, notícias e dicas para todos os níveis de jogadores.', verbose_name='Texto Sobre')),
                ('email_contato', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
