# Generated by Django 6.0 on 2025-12-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='usar_inscritos_automatico',
            field=models.BooleanField(default=False, help_text='Buscar automaticamente da API do YouTube', verbose_name='Usar Inscritos Automático do YouTube'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='youtube_api_key',
            field=models.CharField(blank=True, help_text='Chave de API do Google Cloud Console', max_length=100, verbose_name='YouTube API Key'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='ID do canal do YouTube', max_length=100, verbose_name='YouTube Channel ID'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='inscritos_canal',
            field=models.IntegerField(default=2000, help_text='Número manual ou obtido da API', verbose_name='Inscritos no Canal (Manual)'),
        ),
    ]
