# Generated by Django 6.0 on 2025-12-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracaosite_usar_inscritos_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='desenvolvedor_nome',
            field=models.CharField(blank=True, default='OmegaSistem', max_length=100, verbose_name='Nome do Desenvolvedor'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='desenvolvedor_url',
            field=models.URLField(blank=True, default='https://omegasistem.com.br', verbose_name='URL do Desenvolvedor'),
        ),
    ]
