# Generated by Django 6.0 on 2025-12-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracaosite_desenvolvedor_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='politica_privacidade',
            field=models.TextField(blank=True, help_text='Conteúdo da política de privacidade (aceita HTML)', verbose_name='Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='termos_uso',
            field=models.TextField(blank=True, help_text='Conteúdo dos termos de uso (aceita HTML)', verbose_name='Termos de Uso'),
        ),
    ]
