# Generated by Django 6.0 on 2026-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracaosite_politica_privacidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='politica_privacidade_atualizada',
            field=models.DateField(blank=True, help_text='Última atualização da política', null=True, verbose_name='Data de Atualização da Privacidade'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='termos_uso_atualizado',
            field=models.DateField(blank=True, help_text='Última atualização dos termos', null=True, verbose_name='Data de Atualização dos Termos'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='desenvolvedor_nome',
            field=models.CharField(blank=True, default='OmegaSistem', max_length=100, verbose_name='Desenvolvedor'),
        ),
    ]
