# Generated by Django 6.0 on 2026-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracaosite_politica_privacidade_atualizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticaVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conteudo', models.CharField(choices=[('postagem', 'Postagem'), ('video', 'Vídeo'), ('home', 'Página Inicial')], max_length=20, verbose_name='Tipo de Conteúdo')),
                ('conteudo_id', models.IntegerField(blank=True, help_text='ID da postagem ou vídeo (null para home)', null=True, verbose_name='ID do Conteúdo')),
                ('conteudo_titulo', models.CharField(blank=True, max_length=255, verbose_name='Título do Conteúdo')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Visualização')),
            ],
            options={
                'verbose_name': 'Estatística de Visualização',
                'verbose_name_plural': 'Estatísticas de Visualizações',
                'ordering': ['-data_visualizacao'],
                'indexes': [models.Index(fields=['tipo_conteudo', 'conteudo_id'], name='core_estati_tipo_co_c6db3b_idx'), models.Index(fields=['data_visualizacao'], name='core_estati_data_vi_362c03_idx')],
            },
        ),
    ]
