# Generated by Django 6.0 on 2026-01-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estatisticavisualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticavisualizacao',
            name='data_saida',
            field=models.DateTimeField(blank=True, help_text='Quando o usuário saiu da página', null=True, verbose_name='Data de Saída'),
        ),
        migrations.AddField(
            model_name='estatisticavisualizacao',
            name='scroll_profundidade',
            field=models.IntegerField(default=0, help_text='Porcentagem da página que foi rolada', verbose_name='Profundidade de Scroll (%)'),
        ),
        migrations.AddField(
            model_name='estatisticavisualizacao',
            name='tempo_visualizacao',
            field=models.IntegerField(default=0, help_text='Tempo que o usuário passou na página', verbose_name='Tempo de Visualização (segundos)'),
        ),
    ]
