# Generated by Django 6.0 on 2026-01-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estatisticavisualizacao_data_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='banner_ativo',
            field=models.BooleanField(default=True, help_text='Exibir o banner na página inicial', verbose_name='Banner Ativo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='banner_promocional',
            field=models.ImageField(blank=True, help_text='Banner exibido na home (Tamanho recomendado: 1200x250px)', null=True, upload_to='banners/', verbose_name='Banner Promocional'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='banner_url',
            field=models.URLField(blank=True, help_text='URL para onde o banner deve redirecionar (opcional)', verbose_name='Link do Banner'),
        ),
    ]
